version: "3"
services:
  front:
    build: ./front/
    networks:
      - ingress
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.carthapirates.rule=Host(`carthapirates.fr`)"
      - "traefik.http.routers.carthapirates.entrypoints=websecure"
      - "traefik.http.routers.carthapirates.tls.certresolver=letsencrypt"
  api:
    build: ./api/
    networks:
      - ingress
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.carthapirates_api.rule=Host(`carthapirates.fr`) && PathPrefix(`/api`)"
      - "traefik.http.routers.carthapirates_api.entrypoints=websecure"
      - "traefik.http.routers.carthapirates_api.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.carthapirates_api-stripapiprefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.carthapirates_api.middlewares=carthapirates_api-stripapiprefix@docker"
    environment:
      - ENV_NAME=prod
  db:
    build: ./db/
networks:
  ingress:
    name: gateway_ingress
    external: true